name: Upload scripts and configs to S3
on: [push]
env:
  BUCKET_NAME : "esklv-vpn"
  AWS_REGION : "us-east-2"
permissions:
  id-token: write
  contents: read
jobs:
  S3-Upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::905418258334:role/esklv-vpnS3FullAccessFromGithub
          role-session-name: somename
          aws-region: ${{ env.AWS_REGION }}
      - name: Sync scripts and configs with S3
        run: |
          aws s3 sync ./scripts s3://${{ env.BUCKET_NAME }}/scripts/
          aws s3 sync ./configs s3://${{ env.BUCKET_NAME }}/configs/
      - run: echo "ğŸ This job's status is ${{ job.status }}."